import initScrollSuave from './modules/scroll-suave.js';
initScrollSuave();
import initAnimacaoScroll from './modules/anima-scroll.js';
initAnimacaoScroll();
import intiAccordion from './modules/accordion.js';
intiAccordion();
import intiTabNav from './modules/tabNav.js';
intiTabNav();
import initModal from './modules/modal.js';
initModal();